
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-aws-woo-click-tls
  namespace: argocd
spec:
  secretName: argo-aws-woo-click-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: argo.aws-woo.click
  dnsNames:
  - argo.aws-woo.click